### ISSUE TITLE
Decrease vertical distance between team and "we can help.." section

### ISSUE THREAD

**Issue by bebbi** [gigmade/gigmade.github.io#10]
One test user thought page ended at team and didn't scroll further.

**Comment by ahmedhosny** [comment]
seems equal on top and bottom, no?
reduce all?
![screencapture-file-media-ahmed-dropbox-gigmade-gigmade-github-io-index-html-1483484757728](https://cloud.githubusercontent.com/assets/8398334/21626491/642712c8-d1df-11e6-8f5a-a10b2674cd3f.png)

**Comment by bebbi** [comment]
Agree on that. Perhaps it's that team just "feels" like the last bit.

It's not critical, as anyway my idea was to have a link from dsy to a "we can help" anchor.
