### ISSUE TITLE
Fix 404.

### ISSUE THREAD

**Issue by bebbi** [gigmade/gigmade.github.io#11]

**Comment by ahmedhosny** [comment]
ready to make public?

**Comment by bebbi** [comment]
Sorry for missing body, this issue is about browser 404 for
GET http://www.gigmade.com/fonts/fontawesome-webfont.woff2?v=4.3.0 

Btw, page is live. Unfortunately, no custom SSL in github. So, don't forget to clear HSTS headers or browser will not let you in.
on chrome, go to chrome://net-internals/#hsts
