### ISSUE TITLE
ability to close project view

### ISSUE THREAD

**Issue by bebbi** [gigmade/gigmade.github.io#6]
~~Extend the square minus to the whole screen, except triangles.~~

Probably better: static close button at top right of inner content element. Border around that content element.

Currently there's a very small hidden area on the window that enables returning home so that the accidental visitor wouldn't find it.

**Comment by ahmedhosny** [comment]
does a non-white background color for the slides help?

**Comment by bebbi** [comment]
Users don't figure out how to close the projects detail view, I don't think bg color will improve this.

**Comment by bebbi** [comment]
also, a non-hidden close control will allow consuming the page on a touch device.
