### ISSUE TITLE
Title (We are different & creative) cut in some FF views, overlapping in others.

### ISSUE THREAD

**Issue by bebbi** [gigmade/gigmade.github.io#8]
One of them could be solved by using only a single br tag ?

<img width="653" alt="image" src="https://cloud.githubusercontent.com/assets/2752391/21572240/4a5215ba-ced7-11e6-89b5-3853769c8138.png">
<img width="488" alt="image" src="https://cloud.githubusercontent.com/assets/2752391/21572244/534efc82-ced7-11e6-8ebe-81153b42c427.png">

**Comment by ahmedhosny** [comment]
done
